import React from 'react';
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  scanStyle: {
    width: 300,
    height: 200,
    backgroundColor: 'white',
    margin: 5,
    borderRadius: 10,
  },
  scanStyle2: {
    borderBottomWidth: 1,
    flex: 0.15,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#31B7DE',
  },
  styleNotcn: {
    width: 500,
    height: 250,
    marginBottom: 50,
    backgroundColor: 'red',
    borderRadius: 10,
    borderColor: 'white',
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  styleWaiting: {
    width: 500,
    height: 250,
    marginBottom: 50,
    backgroundColor: '#B79B3F',
    borderRadius: 10,
    borderColor: 'white',
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  connected: {
    width: 500,
    height: 250,
    marginBottom: 50,
    backgroundColor: '#34A753',
    borderRadius: 10,
    borderColor: 'white',
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stop: {
    width: 500,
    height: 250,
    marginBottom: 50,
    backgroundColor: '#6500B2',
    borderRadius: 10,
    borderColor: 'white',
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  normal: {
    width: 500,
    height: 250,
    marginBottom: 50,
    backgroundColor: '#1088AB',
    borderRadius: 10,
    borderColor: 'white',
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  obstacle: {
    width: 500,
    height: 250,
    marginBottom: 50,
    backgroundColor: '#FFAA00',
    borderRadius: 10,
    borderColor: 'white',
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  disconnect: {
    width: 425,
    height: 225,
    marginBottom: 40,
    backgroundColor: '#6500B2',
    borderRadius: 10,
    borderColor: 'white',
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default styles;
